### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by cnfive** [wushidiguo/hello-lottery#6]
我拍了一张四川的双色球票样图，结果就是这样的啊，有问题。

Traceback (most recent call last):
  File "lottery.py", line 139, in <module>
    result = l(opt.image, opt.recognition_only)
  File "lottery.py", line 103, in __call__
    recognition = self.recognize(img, *detection, result_process=True)
  File "lottery.py", line 69, in recognize
    issue = crop(img, issue)[0]
IndexError: list index out of range

**Comment by cnfive** [comment]
![psc](https://github.com/wushidiguo/hello-lottery/assets/37206103/72279b5b-0ead-451d-af3e-9ce91166fae5)
无法识别这个图片，提示IndexError: list index out of range
